SET NAMES UTF8;
DROP DATABASE IF EXISTS lmt;
CREATE DATABASE lmt CHARSET=UTF8;
USE lmt;
CREATE TABLE user (
    uno INT PRIMARY KEY AUTO_INCREMENT,
    uname VARCHAR(32),
    upwd VARCHAR(32)
);
INSERT INTO user VALUES(1,"李","123456");